spring:
  #to enable colors when you run your app outside intellij
  output:
    ansi:
      enabled: always

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/task_flow?createDatabaseIfNotExist=true
    username: root
    password:
  liquibase:
    change-log: db/changelog/master.xml
    enabled: true
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    generate-ddl: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970